-- MySQL Script generated by MySQL Workbench
-- Thu Feb 15 15:29:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eduardo-servico_ti_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eduardo-servico_ti_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eduardo-servico_ti_bd` DEFAULT CHARACTER SET utf8 ;
USE `eduardo-servico_ti_bd` ;

-- -----------------------------------------------------
-- Table `eduardo-servico_ti_bd`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eduardo-servico_ti_bd`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `processador` VARCHAR(45) NULL,
  `placamae` VARCHAR(45) NULL,
  `fonte` VARCHAR(45) NULL,
  `ram` VARCHAR(45) NULL,
  `video` VARCHAR(45) NULL,
  `acessorios` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `dataentrada` VARCHAR(45) NULL,
  `orcamento` VARCHAR(45) NULL,
  `obsevacao` VARCHAR(500) NULL,
  `queixa` VARCHAR(500) NULL,
  PRIMARY KEY (`idclientes`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
